# Session 1 (Part 2)


## Importing Modules
If vanilla python seems rather lackluster, that's because it is. Fortunately, the scientific stack adds a broad and powerful array of python packages fill in the gaps. Once installed, packages in python are easily loaded for use.

In [1]:
import numpy as np
print(np.__version__)

1.18.1


Commands from packages are like attributes of objects. For convenience, we will import packages using shorthand.

## NumPy Arrays
Arrays are the most basic type of the NumPy package. NumPy arrays are vectors (Nx1), similar to pythonic lists. In contrast to lists, however, arrays have many more attributes and can be modified in substantially more ways. Several examples are provided below demonstrating the improvement of arrays over lists.

In contrast, NumPy arrays can be modified in this way. We use the `np.arange` command to initialize an array of sequential integers.

In [2]:
arr = np.arange(5)

print(arr, type(arr))
print(arr * 3)
print(arr * arr)

[0 1 2 3 4] <class 'numpy.ndarray'>
[ 0  3  6  9 12]
[ 0  1  4  9 16]


Every array has an object type. These can be looked up and modified.

In [3]:
print(arr, arr.dtype)   # Print current datatype.
arr = arr.astype(float) # Conver to float.
print(arr, arr.dtype)   # Print new datatype.

[0 1 2 3 4] int64
[0. 1. 2. 3. 4.] float64


Numpy arrays store metadata about their contents. These can be helpful, especially the **shape** atribute.

In [4]:
print('Array shape:', arr.shape) # Print shape of array.
print('Array size:', arr.size)  # Print number of total elements.

Array shape: (5,)
Array size: 5


Accessing elements is easy.

In [5]:
print(arr[:2])
print(arr[[1,3,4]])

[0. 1.]
[1. 3. 4.]


Arrays now have a number of other built-in attributes 
not available for lists.

In [6]:
print('Round:', arr.round()) # Round array.
print('Min:', arr.min())     # Get max of array.
print('Max:', arr.max())     # Get min of array.
print('Sum:', arr.sum())     # Get sum of array.
print('Mean:',arr.mean())    # Get mean of array.

Round: [0. 1. 2. 3. 4.]
Min: 0.0
Max: 4.0
Sum: 10.0
Mean: 2.0


## NumPy Matrices
It is possible to represent matrices in pythonic lists, though it is inefficient. Similar to the benefits of arrays, NumPy matrices dramatically improve upon the numerical capabilities of core python. Python can technically represent matrices as a list of lists.

In [7]:
nested_lists = [[1,2,3],
                [4,5,6],
                [7,8,9]]

print(nested_lists)
print(nested_lists[1][2])   # To extract the 2nd row, 3rd column, two brackets are necessary.

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
6


NumPy matrices make this much easier!

In [8]:
mat = np.array(nested_lists)

print(mat)
print(mat[1,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


Indexing of NumPy matrices (and arrays for that matter) obey all of the slicing conventions of lists. Commas are used to demarcate which axis a slice operation is targeting.

In [9]:
print('mat[1,2]  = %s' %mat[1,2])    # Second row, third column.
print('mat[0,:]  = %s' %mat[0,:])    # All the first row.
print('mat[:,-1] = %s' %mat[:,-1])   # All of the final column.

mat[1,2]  = 6
mat[0,:]  = [1 2 3]
mat[:,-1] = [3 6 9]


NumPy matrices have all the same attributes of NumPy arrays, but now functions can be applied to specific rows or columns in addition to the entire matrix.

In [10]:
## Sum across matrix.
print( mat.sum() )          

45


In [11]:
## Sum across columns.
print( mat.sum(axis=0) )

[12 15 18]


In [12]:
## Sum across rows.
print( mat.sum(axis=1) )

[ 6 15 24]


Importantly, all NumPy arrays and matrices have a **reshape** attribute allowing for transforming matrices into different dimensions.

In [13]:
print('Original shape', mat.shape)

# Reshape to column vector
mat = mat.reshape(9,1)
print('Column vector', mat.shape)

# Reshape to column vector
mat = mat.reshape(1,9)
print('Row vector', mat.shape)

Original shape (3, 3)
Column vector (9, 1)
Row vector (1, 9)


Importantly, reshape can be used to change the shape of NumPy arrays. The order flag can also change how they are organized (row-ordered vs. column-ordered).

In [14]:
print('Original:', mat)

Original: [[1 2 3 4 5 6 7 8 9]]


In [15]:
## Reshape (column organized)
print(mat.reshape(3,3,order='C'))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
## Reshape (row organized)
print(mat.reshape(3,3,order='F')) 

[[1 4 7]
 [2 5 8]
 [3 6 9]]


The dimensions of matrices can also be quickly changed with **flatten** and **squeeze**. 

In [17]:
## Reshape to new dimensions.
mat = mat.reshape(3,3,1)
print('Original:', mat.shape)

## Flatten matrix.
print('Flatten:', mat.flatten().shape )

## Squeeze matrix.
print('Squeeze:', mat.squeeze().shape )

Original: (3, 3, 1)
Flatten: (9,)
Squeeze: (3, 3)


## Generating NumPy Arrays
Just as with arrays, there are a number of ways of generating NumPy matrices. The simplest is to use the **array** command on a list or list of lists. 

In [18]:
## Making an array from a list using the array command.
example_list = [4, 7, 9.4]
arr = np.array(example_list)

print(example_list, type(example_list))
print(arr, type(arr)) 

[4, 7, 9.4] <class 'list'>
[4.  7.  9.4] <class 'numpy.ndarray'>


NumPy has recreated all of the standard R/Matlab commands for 
generating arrays.

In [19]:
print('np.arange(5)        = %s' %np.arange(5))         # Array of 5 sequential integers.
print('np.zeros(5)         = %s' %np.zeros(5))          # Array of 5 zeros.
print('np.ones(5)          = %s' %np.ones(5))           # Array of 5 ones.
print('np.linspace(0,10,5) = %s' %np.linspace(0,10,5))  # Length-5 evenly-spaced array from 0 to 10.
print('np.logspace(0,2,5) = %s' %np.logspace(0,2,5))    # Length-5 logarithmically-spaced array.

np.arange(5)        = [0 1 2 3 4]
np.zeros(5)         = [0. 0. 0. 0. 0.]
np.ones(5)          = [1. 1. 1. 1. 1.]
np.linspace(0,10,5) = [ 0.   2.5  5.   7.5 10. ]
np.logspace(0,2,5) = [  1.           3.16227766  10.          31.6227766  100.        ]


The same commands previously introduced to generate NumPy arrays can also be used to generate matrices. Simply specify extra dimensions.

In [20]:
np.zeros( [3,3] )               # 3x3 matrix of zeros.
np.ones( [3,3] )                # 3x3 matrix of ones.
np.arange(9).reshape(3,3)       # 3x3 matrix of sequential integers.
np.linspace(0,8,9).reshape(3,3) # 3x3 matrix evenly-spaced array from 0 to 8. 
np.identity(3)                  # 3x3 identity matrix.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Matrices can also be formed by joining NumPy arrays. There are several methods for doing this, including: `row_stack`/`r_`, `column_stack`/`c_`, `hstack`, `vstack`, and `concatenate`. We demonstrate each below. 

In [21]:
arr = np.arange(5)
print(arr)

## Join rows.
rows = np.row_stack([arr,arr])
print(rows)

## Join columns.
cols = np.column_stack([arr,arr])
print(cols)

[0 1 2 3 4]
[[0 1 2 3 4]
 [0 1 2 3 4]]
[[0 0]
 [1 1]
 [2 2]
 [3 3]
 [4 4]]


In [22]:
np.stack;          # join arrays along column or rows.
np.hstack;         # join arrays along their columns
np.vstack;         # join arrays along their rows.
np.concatenate;    # join arrays along single axis.

In a pinch, one can also use `np.array` to concatenate arrays along the first axis.

In [23]:
print(np.array([arr,arr]))

[[0 1 2 3 4]
 [0 1 2 3 4]]


## Indexing, Masking, and Assignments

NumPy supports a great many ways of indexing.

In [24]:
## Set the RNG seed!
np.random.seed(47404)

## Construct an arbitrary matrix.
mat = np.random.randint(0,10,(10,10))

## Access particular rows.
mat[:1]

## Access particular columns.
mat[:,:5]

## Access particular rows/columns.
mat[:5,5:]

## Access using lists of indexes.
mat[[1,3,5],[5,1,2]]

array([6, 1, 1])

Far more useful is indexing with boolean arrays.

In [25]:
## Return all elements of matrix that meet criterion.
mat[mat > 5]

## Return all rows that begin with particular integer.
mat[mat[:,0] == 1]

## Return all columns whose sum is greater than 40.
mat[:,mat.sum(axis=0) > 40]

array([[0, 2, 0, 3, 4, 5],
       [9, 8, 3, 8, 7, 0],
       [3, 6, 7, 3, 3, 3],
       [1, 7, 0, 4, 6, 6],
       [5, 5, 9, 1, 9, 1],
       [5, 1, 8, 1, 7, 9],
       [4, 1, 5, 0, 5, 8],
       [9, 0, 9, 7, 9, 4],
       [9, 6, 8, 8, 2, 5],
       [2, 9, 6, 6, 0, 7]])

For larger matrices, we can use the ellipsis as a shorthand.

In [26]:
mat = np.random.randint(0,9,(5,5,5,5))
mat[0,...,-1]

array([[4, 2, 7, 4, 8],
       [2, 4, 7, 7, 7],
       [1, 7, 3, 3, 0],
       [2, 3, 1, 3, 2],
       [5, 1, 4, 6, 8]])

Like pythonic lists, we can update NumPy arrays in place.

In [27]:
## Construct an arbitrary matrix.
mat = np.random.randint(0,10,(10,10))

## Update first element.
mat[0,0] = 99

## Update full row.
mat[3,:] = -99

## Update multiple columns.
mat[:,-2:] = 0

This also allows for convenient masking.

In [28]:
mat[mat < 5 ] = 0
mat

array([[99,  7,  0,  5,  9,  7,  0,  0,  0,  0],
       [ 0,  0,  8,  6,  7,  6,  0,  5,  0,  0],
       [ 0,  5,  0,  9,  5,  0,  0,  7,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 7,  6,  6,  8,  7,  0,  0,  7,  0,  0],
       [ 0,  9,  7,  0,  0,  0,  0,  0,  0,  0],
       [ 6,  0,  0,  6,  9,  6,  8,  0,  0,  0],
       [ 0,  0,  5,  7,  9,  8,  0,  0,  0,  0],
       [ 7,  8,  5,  8,  0,  5,  0,  0,  0,  0],
       [ 0,  8,  6,  9,  7,  8,  5,  0,  0,  0]])

For a complete list of convenient routines, see the [NumPy indexing documentation](https://docs.scipy.org/doc/numpy/user/basics.indexing.html#).

## Core NumPy Functions
NumPy also introduces a [number of useful functions](https://docs.scipy.org/doc/numpy/reference/) designed to operate efficiently over NumPy arrays. The following is a non-exhaustive overview of some important NumPy functions.

#### Mathematical functions

NumPy includes a variety of mathematical functions. All of these can be applied across an entire matrix or across arrays.

In [29]:
np.sum;       # Sum of an array or matrix.
np.cumsum;    # Cumulative sum over an array.
np.prod;      # Element-wise multiplication of an array.
np.divide;    # Element-wise division of two arrays.
np.diff;      # Pairwise difference of elements of an array.
np.exp;       # Exponential transform.
np.log;       # Natural logarithm.
np.log10;     # Base-10 logarithm.

#### Rounding Functions

In [30]:
mat = np.linspace(0,1,5)
print('Original: %s' %mat)
print('np.round: %s' %np.round(mat, 1) )
print('np.floor: %s' %np.floor(mat) ) 
print('np.ceil:  %s' %np.ceil(mat) )

Original: [0.   0.25 0.5  0.75 1.  ]
np.round: [0.  0.2 0.5 0.8 1. ]
np.floor: [0. 0. 0. 0. 1.]
np.ceil:  [0. 1. 1. 1. 1.]


#### Summary Functions

NumPy includes many functions to summarize an array. With the exception of `np.corrcoef`, all of these can be
applied across an entire matrix or across arrays.

In [31]:
np.min;           # Return the smallest element.
np.max;           # Return the largest element.
np.argmin;        # Return the index of the smallest element.
np.argmax;        # Return the index of the largest element.
np.mean;          # Compute the mean of an array.
np.median;        # Compute the median of an array.
np.std;           # Compute the standard deviation of an array.
np.var;           # Compute the variance (sd^2) of an array.
np.percentile;    # Compute the xth percentile of an array.
np.corrcoef;      # Compute the row-/col-wise correlation of a matrix.

#### Set Functions
NumPy includes functions for identifying unique elements within or between arrays.

In [32]:
## Define two arrays for example.
arr1 = np.array([41, 16, 34, 0, 2, 20, 19, 14, 22, 15, 18, 9, 35, 41])
arr2 = np.array([42, 22, 40, 7, 33, 0, 12, 19, 44, 10, 31, 11, 11, 49])

In [33]:
## Sort elements (ascending order).
np.sort(arr1)

array([ 0,  2,  9, 14, 15, 16, 18, 19, 20, 22, 34, 35, 41, 41])

In [34]:
## Return unique elements.
np.unique(arr1)

array([ 0,  2,  9, 14, 15, 16, 18, 19, 20, 22, 34, 35, 41])

In [35]:
## Return unique elements, count number of appearances.
np.unique(arr1, return_counts=True)

(array([ 0,  2,  9, 14, 15, 16, 18, 19, 20, 22, 34, 35, 41]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2]))

In [36]:
## Find the elements of array-1 in array-2.
np.in1d(arr1, arr2)

array([False, False, False,  True, False, False,  True, False,  True,
       False, False, False, False, False])

In [37]:
## Return all unique elements of arrays 1 & 2.
np.union1d(arr1, arr2)

array([ 0,  2,  7,  9, 10, 11, 12, 14, 15, 16, 18, 19, 20, 22, 31, 33, 34,
       35, 40, 41, 42, 44, 49])

In [38]:
## Return all elements belonging to both arrays 1 & 2.
np.intersect1d(arr1, arr2)

array([ 0, 19, 22])

## Replacing List Comprehensions

NumPy includes a number of very helpful functions that act to replace list comprehensions (np.where) and for loops (np.apply_across_axis, np.apply_over_axes). These are often more efficient than writing out a full For loop. We will emphasize these functions with a simple example of standard-scoring (z-scoring) a matrix.

In [39]:
## Define the standard score (z-score) function.
def zscore(arr): 
    return (arr - arr.mean()) / arr.std()

## Define a simple matrix.
mat = np.arange(12).reshape(2,6)
print(mat)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


Use `np.apply_across_axis` to apply our function across each row.

In [40]:
zmat = np.apply_along_axis(zscore, axis=1, arr=mat)
print(zmat.round(2))

[[-1.46 -0.88 -0.29  0.29  0.88  1.46]
 [-1.46 -0.88 -0.29  0.29  0.88  1.46]]


Use the `np.where` command to set all negative numbers to 0, else 1. 

In [41]:
amat = np.where(zmat < 0, 0, 1)
print(amat)

[[0 0 0 1 1 1]
 [0 0 0 1 1 1]]


If no transforms are specified, `np.where` returns the indices of the array where the conditional is met.

In [42]:
print( np.where(zmat < 0 ) )

(array([0, 0, 0, 1, 1, 1]), array([0, 1, 2, 0, 1, 2]))


This also means `np.where` is especially useful for indexing and masking!

In [43]:
mat[zmat > 0]

array([ 3,  4,  5,  9, 10, 11])

## Matrix Math

NumPy supports matrix operations. The simplest operator is transposition.

In [44]:
## Generate random matrix.
X = np.random.normal(0,1,(5,5))

print(X)      # Print original matrix.
print(X.T)    # Print transposed matrix.

[[ 0.74870017  0.17009284 -1.55704802  0.6663686  -0.23960664]
 [ 0.31441717 -0.62799089  0.13503709 -1.14103616 -0.74820447]
 [ 0.62186404 -0.28863985  0.42554203 -0.63336091 -0.14600351]
 [ 1.72994316  0.12359513  0.41872901 -0.17774351  0.03019599]
 [ 0.07238011  2.52815271  0.69858317 -0.27696547 -0.10882994]]
[[ 0.74870017  0.31441717  0.62186404  1.72994316  0.07238011]
 [ 0.17009284 -0.62799089 -0.28863985  0.12359513  2.52815271]
 [-1.55704802  0.13503709  0.42554203  0.41872901  0.69858317]
 [ 0.6663686  -1.14103616 -0.63336091 -0.17774351 -0.27696547]
 [-0.23960664 -0.74820447 -0.14600351  0.03019599 -0.10882994]]


The shorthand for matrix multiplication uses the **@** operator.

In [45]:
X @ X

array([[ 7.81196923e-01, -5.34443609e-02, -1.69373995e+00,
         1.23892161e+00, -3.31252420e-02],
       [-1.90615504e+00, -1.62372608e+00, -1.51736872e+00,
         1.25058940e+00,  4.21785588e-01],
       [-4.66780443e-01, -2.83190067e-01, -1.19336542e+00,
         6.27231213e-01,  1.59283977e-03],
       [ 1.28916110e+00,  1.50144291e-01, -2.55205981e+00,
         7.69776211e-01, -5.76769559e-01],
       [ 7.96497733e-01, -2.08635475e+00,  3.33971335e-01,
        -3.19956615e+00, -2.00743279e+00]])

The **@** operator can be substituted with ``np.dot``. 

In [46]:
## Matrix multiplcation (v1).
v1 = np.dot(X,X)

## Matrix multiplcation (v2).
v2 = X.dot(X)

## Assert all equal.
np.all(v1 == v2)

True

Similarly, NumPy supports inner and outer products.

In [47]:
x = np.random.normal(0,1,size=5)

## Inner product.
inner = np.inner(x,x)
print(inner)

## Outer product.
outer = np.outer(x,x)
print(outer)

4.975035263824731
[[ 2.44401071e-01  8.53521805e-01  2.08950095e-02 -1.88721690e-01
   6.25795584e-01]
 [ 8.53521805e-01  2.98075401e+00  7.29716370e-02 -6.59072715e-01
   2.18546578e+00]
 [ 2.08950095e-02  7.29716370e-02  1.78641370e-03 -1.61347145e-02
   5.35022396e-02]
 [-1.88721690e-01 -6.59072715e-01 -1.61347145e-02  1.45727169e-01
  -4.83227015e-01]
 [ 6.25795584e-01  2.18546578e+00  5.35022396e-02 -4.83227015e-01
   1.60236660e+00]]


## Linear Algebra Functions

NumPy includes an entire submodule dedicated to efficient linear algebra functions (though it should be noted that SciPy has reimplemented them for maximal efficiency). See np.linalg for a full list of commands.

In [48]:
## Define a simple matrix.
mat = np.arange(16).reshape(4,4)
print(mat)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [49]:
## Return diagonal of matrix
print(np.diag(mat))

[ 0  5 10 15]


In [50]:
## Return upper triangular matrix
print(np.triu(mat))    

[[ 0  1  2  3]
 [ 0  5  6  7]
 [ 0  0 10 11]
 [ 0  0  0 15]]


In [51]:
## Matrix multiply itself. Can also np.dot.
print(np.dot(mat, mat))    

[[ 56  62  68  74]
 [152 174 196 218]
 [248 286 324 362]
 [344 398 452 506]]


In [52]:
## Can also use:
print(mat.dot(mat))

[[ 56  62  68  74]
 [152 174 196 218]
 [248 286 324 362]
 [344 398 452 506]]


In [53]:
## Linear algebra operations include:
np.linalg.norm;        # Vector or matrix norm
np.linalg.inv;         # Inverse of a square matrix
np.linalg.det;         # Determinant of a square matrix
np.linalg.eig;         # Eigenvalues and vectors of a square matrix
np.linalg.cholesky;    # Cholesky decomposition of a matrix
np.linalg.svd;         # Singular value decomposition of a matrix
np.linalg.lstsq;       # Solve linear least-squares problem

## Brief Note on NaNs

NumPy has a unique NaN class. `np.nan` dominates all other numeric types.

In [54]:
print(7. * np.nan)              # NaN dominates numeric types.
print(np.arange(5) * np.nan)    # NaN dominates numeric arrays.

nan
[nan nan nan nan nan]


NaNs may appear wherever there is missing data, or when an operation returns an invalid number.

In [55]:
## Example array.
arr = np.arange(15,dtype=float).reshape(3,5)
arr[1,-1] = np.nan
print(arr)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8. nan]
 [10. 11. 12. 13. 14.]]


NaNs can be challenging because they corrupt most standard routines.

In [56]:
print(arr.max(axis=1))     # NaNs corrupt max.
print(arr.mean(axis=1))    # NaNs corrupt mean.
print(arr.std(axis=1))     # NaNs corrupt standard deviation.

[ 4. nan 14.]
[ 2. nan 12.]
[1.41421356        nan 1.41421356]


NumPy offers a suite of NaN robust functions. These are slower, but can be useful in analysis.

In [57]:
print(np.nanmax(arr, axis=1))     # NaN robust max.
print(np.nanmean(arr, axis=1))    # NaN robust mean.
print(np.nanstd(arr, axis=1))     # NaN robust standard deviation.

[ 4.  8. 14.]
[ 2.   6.5 12. ]
[1.41421356 1.11803399 1.41421356]
